[[plugins]]
package = "netlify-plugin-checklinks"

  [plugins.inputs]
  entryPoints = [
    "*.html",
  ]

  recursive = true

  pretty = true

  skipPatterns = [
    "about/data/'https:/www.scouts.org.uk/about-us/policy/data-protection-policy/'",
  ]

  todoPatterns = []

  checkExternal = false

  followSourceMaps = false