[[plugins]]
package = "netlify-plugin-checklinks"

  [plugins.inputs]
    entryPoints = [
      "*.html",
    ]
    skipPatterns = [
      "about/data"
    ]
    recursive = true
    pretty = true
    checkExternal = false
    followSourceMaps = false