[[redirects]]
  from = "/about/data"
  to = "https://www.scouts.org.uk/about-us/policy/data-protection-policy/"
  status = 301
  force = false

[[redirects]]
  from = "/squirrels"
  to = "https://squirrels.pnsg.org.uk"
  status = 301
  force = false

[[redirects]]
  from = "/sections/squirrels"
  to = "https://squirrels.pnsg.org.uk"
  status = 301
  force = false

[[redirects]]
  from = "/beavers"
  to = "https://beavers.pnsg.org.uk"
  status = 301
  force = false

[[redirects]]
  from = "/sections/beavers"
  to = "https://beavers.pnsg.org.uk"
  status = 301
  force = false

[[redirects]]
  from = "/cubs"
  to = "https://cubs.pnsg.org.uk"
  status = 301
  force = false

[[redirects]]
  from = "/sections/cubs"
  to = "https://cubs.pnsg.org.uk"
  status = 301
  force = false

[[redirects]]
  from = "/scouts"
  to = "https://scouts.pnsg.org.uk"
  status = 301
  force = false

[[redirects]]
  from = "/sections/scouts"
  to = "https://scouts.pnsg.org.uk"
  status = 301
  force = false

[[redirects]]
  from = "/explorers"
  to = "https://explorers.pnsg.org.uk"
  status = 301
  force = false

[[redirects]]
  from = "/sections/explorers"
  to = "https://explorers.pnsg.org.uk"
  status = 301
  force = false

[[plugins]]
  package = "netlify-plugin-a11y"

  [plugins.inputs]
    checkPaths = ['/']
    ignoreDirectories = []

[[plugins]]
package = "netlify-plugin-checklinks"

  [plugins.inputs]
    entryPoints = [
      "*.html",
    ]
    skipPatterns = [
      "about/data"
    ]
    recursive = true
    pretty = true
    checkExternal = false
    followSourceMaps = false

[[plugins]]
package = "netlify-plugin-chromium"

  [plugins.inputs]
    packageManager = "npm"
    setChromePathInEnv = true
    failBuildOnError = false

[[plugins]]
  package = "netlify-plugin-html-validate"

  [plugins.inputs]
    ext = "html"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "netlify-plugin-minify-html"

  [plugins.inputs.minifierOptions]
    removeComments = true
    collapseInlineTagWhitespace = true

[[plugins]]
package = "netlify-plugin-no-more-404"

  [plugins.inputs]
    on404 = "error" 
    cacheKey = "00001"
    debugMode = true

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
    prettyURLs = true
    trailingSlash = true

[[plugins]]
package = "netlify-plugin-subfont"

  [plugins.inputs]
  entryPoints = [
    "*.html",
  ]
  recursive = true
  fontDisplay = "swap"
  inlineCss = false
  inlineFonts = false
  fallbacks = true
  
[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]
	baseUrl = "default"
	sitemapPath = "default"
	ignorePeriod = 0
	providers = [
		"google",
		"yandex"
	]